### ISSUE TITLE
Game of 1's and 0's.

### ISSUE THREAD

**Issue by aneels3** [aneels3/Algorithm#12]
Take a number and invert the binary ones with 0's and vice versa.
Rules:
1) If the binary 1 in the number is consecutive ->no inversion. 
2) If the binary 0 in the number is consecutive -> inversion
3) stops the process, If rules 1 and 2 get overruled. 
4) Print "WON" if the Inverted decimal equivalent number is greater than the initial number else print "LOST"

**Comment by vivekshah1801** [comment]
Hello @aneels3, I would like to contribute to this. can you please elaborate more on the problem?

**Comment by aneels3** [comment]
hello @vivekshah1801 
I am assigning you to this issue.

The problem statement is simple and easy.
for eg.

suppose you have a number n(say) = 4.
so its binary equivalent is equal to 100

First, you have to invert the 1 as it is not consecutive.
so after inversion your n = 000

now as there are consecutive 0's, as per rule 2 you need to invert it to 111.

As the number is now 111 both rules get overruled.
Hence you have to stop the iteration and analyze the final value and the initial value and print the message.
