### ISSUE TITLE
Circular Rotation

### ISSUE THREAD

**Issue by aneels3** [aneels3/Algorithm#13]
Right Circular Rotation

**Comment by hetpandya98** [comment]
Hello @aneels3 . I would like to contribute to this problem. Please describe the problem statement.

**Comment by aneels3** [comment]
hey @hetpandya98 
I am assigning you to this issue.
The problem statement is simple.
Take one list of n elements and rotate right it by an input k.

**Comment by nancyanand2807** [comment]
hello @aneels3  I would also like to contribute to this problem.

**Comment by aneels3** [comment]
Assigned to @nancyanand2807

**Comment by nancyanand2807** [comment]
Done as per the requirements.!! @aneels3

**Comment by hetpandya98** [comment]
Task completed. Please accept PR #68 @aneels3 .
