### ISSUE TITLE
Solve Any HackerRank Algorithm Problem

### ISSUE THREAD

**Issue by aneels3** [aneels3/Algorithm#28]
Solve a HackerRank problem.
Language Allowed
1) C
2) C++
3) Java
4) Python
5) Ruby

See the [contribution guidelines](https://github.com/aneels3/Algorithm/blob/master/CONTRIBUTION.md)
PR should have the problem name and should be placed in the proper language directory.
Committed code should run in the HackerRank platform.

**Comment by MediMESS** [comment]
Hello is there any hankRank algorithm i can contribute with?

**Comment by MediMESS** [comment]
Hello i would like to work on this, do you have a specific algorithm in mind, maybe i can go spcifically to it

**Comment by aneels3** [comment]
hello @MediMESS ,
please go through this [Algorithm](urlhttps://www.hackerrank.com/domains/algorithms) pick any question from it, solve it and send the PR.

**Comment by MediMESS** [comment]
@aneels3, Ok thank you, i will pick one and work on it immediately 👍

**Comment by aneels3** [comment]
@MediMESS Great!

**Comment by Ahelii16** [comment]
Hi, I'd like to work on this too!

**Comment by SirBob01** [comment]
Hi! I'd like to work on this!

**Comment by Surya97** [comment]
Hi! Can I work on this?

**Comment by Nikita-Sukhwal** [comment]
Hello @aneels3 !
I would like to work on - [Inherited Code](https://www.hackerrank.com/challenges/inherited-code/problem) of C++. Can you please assign me for this.

**Comment by aneels3** [comment]
@Nikita-Sukhwal pick any problem from the HackerRank and contribute the solution.
