### ISSUE TITLE
The Blacklist Problem [Difficulty-Advanced][DP-Hackerrank]

### ISSUE THREAD

**Issue by dhruvhacks** [aneels3/Algorithm#44]
I would like to contribute the solution for [The Blacklist Problem](https://www.hackerrank.com/challenges/the-blacklist/problem) of HackerRank.

Difficulty level- **Advanced**
Algorithm Section:- **Dynamic Programming**

Please Assign!!

**Comment by aneels3** [comment]
#44 Assigned to @dhruvhacks
