### ISSUE TITLE
[HackerRank] Fibonacci Modified

### ISSUE THREAD

**Issue by ravinalawade** [aneels3/Algorithm#49]
I would like to do my first open source contribution on a Hackerrank problem based on Dynamic programming approach.

Problem name-Fibonacci Modified
Difficulty -Medium (Max score-45 points)

Please assign me on this problem as I am eager to do my first open source contribution.

**Comment by aneels3** [comment]
Assigned to @ravinalawade

**Comment by ravinalawade** [comment]
thank you for assigning me the problem

**Comment by aneels3** [comment]
@ravinalawade
